// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQ1SVKQAbqTWMouYwhDsgujyX2cOIJRjU',
    appId: '1:37837355921:web:7c561ed6686cb430393830',
    messagingSenderId: '37837355921',
    projectId: 'explorer-ef6bc',
    authDomain: 'explorer-ef6bc.firebaseapp.com',
    databaseURL: 'https://explorer-ef6bc-default-rtdb.firebaseio.com',
    storageBucket: 'explorer-ef6bc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjynqs5iDQ2iWyXIGfQ2lRBfKpbBLsvL4',
    appId: '1:37837355921:android:b42ed73c1e3d43d7393830',
    messagingSenderId: '37837355921',
    projectId: 'explorer-ef6bc',
    databaseURL: 'https://explorer-ef6bc-default-rtdb.firebaseio.com',
    storageBucket: 'explorer-ef6bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0q-gqIfYEQ_50hCaALqtLvrP4QnpLiDU',
    appId: '1:37837355921:ios:9c7551882f71ce21393830',
    messagingSenderId: '37837355921',
    projectId: 'explorer-ef6bc',
    databaseURL: 'https://explorer-ef6bc-default-rtdb.firebaseio.com',
    storageBucket: 'explorer-ef6bc.appspot.com',
    iosBundleId: 'com.bot.smartcoin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0q-gqIfYEQ_50hCaALqtLvrP4QnpLiDU',
    appId: '1:37837355921:ios:9c7551882f71ce21393830',
    messagingSenderId: '37837355921',
    projectId: 'explorer-ef6bc',
    databaseURL: 'https://explorer-ef6bc-default-rtdb.firebaseio.com',
    storageBucket: 'explorer-ef6bc.appspot.com',
    iosBundleId: 'com.bot.smartcoin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQ1SVKQAbqTWMouYwhDsgujyX2cOIJRjU',
    appId: '1:37837355921:web:c8283c0ed96976ba393830',
    messagingSenderId: '37837355921',
    projectId: 'explorer-ef6bc',
    authDomain: 'explorer-ef6bc.firebaseapp.com',
    databaseURL: 'https://explorer-ef6bc-default-rtdb.firebaseio.com',
    storageBucket: 'explorer-ef6bc.appspot.com',
  );
}
